EJUDGE_OK = 'OK'  # OK
EJUDGE_PT = 'PT'  # Partial score
EJUDGE_WA = 'WA'  # Wrong answer
EJUDGE_RT = 'RT'  # Runtime error
EJUDGE_TL = 'TL'  # Time limit exceeded
EJUDGE_PE = 'PE'  # Presentation error
EJUDGE_ML = 'ML'  # Memory limit exceeded
EJUDGE_SE = 'SE'  # Security violation
EJUDGE_CE = 'CE'  # Compilation error
EJUDGE_CF = 'CF'  # Check failed
EJUDGE_AC = 'AC'  # Accepted
EJUDGE_IG = 'IG'  # Ignored
EJUDGE_PD = 'PD'  # Pending
EJUDGE_SV = 'SV'  # Style violation
EJUDGE_WT = 'WT'  # Wall time limit exceeded
EJUDGE_PR = 'PR'  # Pending review
EJUDGE_SM = 'SM'  # Summoned for defence
EJUDGE_RJ = 'RJ'  # Rejected
EJUDGE_RU = 'RU'  # Running

EJUDGE_VIRTUAL_START = 'VS'
EJUDGE_VIRTUAL_STOP = 'VT'

EJUDGE_BAD_VERDICTS = [EJUDGE_WA, EJUDGE_RT, EJUDGE_TL, EJUDGE_PE, EJUDGE_ML, EJUDGE_SE, EJUDGE_PT, EJUDGE_WT]
BLITZ_PENDING = 'BP'  # Pending submission
BLITZ_TE = 'TE'  # Time exceeded


CODEFORCES_OK = 'OK'
CODEFORCES_PT = 'PARTIAL'
CODEFORCES_WA = 'WRONG_ANSWER'
CODEFORCES_RT = 'RUNTIME_ERROR'
CODEFORCES_TL = 'TIME_LIMIT_EXCEEDED'
CODEFORCES_PE = 'PRESENTATION_ERROR'
CODEFORCES_ML = 'MEMORY_LIMIT_EXCEEDED'
CODEFORCES_SE = 'SECURITY_VIOLATED'
CODEFORCES_CF = 'FAILED'
CODEFORCES_CE = 'COMPILATION_ERROR'
CODEFORCES_IL = 'IDLENESS_LIMIT_EXCEEDED'
CODEFORCES_RJ = 'REJECTED'
CODEFORCES_CR = 'CRASHED'
CODEFORCES_IC = 'INPUT_PREPARATION_CRASHED'
CODEFORCES_SM = 'CHALLENGED'
CODEFORCES_RU = 'TESTING'

CODEFORCES_EJUDGE_VERDICTS = {
    CODEFORCES_OK: EJUDGE_OK,
    CODEFORCES_PT: EJUDGE_PT,
    CODEFORCES_WA: EJUDGE_WA,
    CODEFORCES_RT: EJUDGE_RT,
    CODEFORCES_TL: EJUDGE_TL,
    CODEFORCES_PE: EJUDGE_PE,
    CODEFORCES_ML: EJUDGE_ML,
    CODEFORCES_SE: EJUDGE_SE,
    CODEFORCES_CF: EJUDGE_CF,
    CODEFORCES_CE: EJUDGE_CE,
    CODEFORCES_IL: EJUDGE_TL,
    CODEFORCES_RJ: EJUDGE_RJ,
    CODEFORCES_CR: EJUDGE_RT,
    CODEFORCES_IC: EJUDGE_CF,
    CODEFORCES_SM: EJUDGE_SM,
    CODEFORCES_RU: EJUDGE_RU
}

