# Generated by Django 2.1.2 on 2018-10-23 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=300)),
                ('ejudge_id', models.IntegerField()),
                ('olymp', models.BooleanField(default=False)),
                ('statements', models.FileField(blank=True, upload_to='docs')),
                ('show_statements_link', models.BooleanField(default=False)),
                ('duration', models.IntegerField(default=100000)),
                ('other_link', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ContestLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('file', models.FileField(blank=True, upload_to='docs')),
                ('link', models.CharField(blank=True, max_length=300)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cource.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('subtitle', models.TextField(blank=True)),
                ('ejudge_url', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LeftLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('file', models.FileField(blank=True, upload_to='docs')),
                ('link', models.CharField(blank=True, max_length=300)),
                ('hidden', models.BooleanField(default=False)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cource.Course')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='cource.Course'),
        ),
    ]
