# Generated by Django 2.1.2 on 2018-11-16 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battleship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('contest', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BattleshipTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('battleship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='cource.Battleship')),
            ],
        ),
        migrations.CreateModel(
            name='ShipPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='cource.BattleshipTeam')),
            ],
        ),
        migrations.CreateModel(
            name='UserId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ids', to='cource.BattleshipTeam')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='coefficient',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='contest',
            name='duration',
            field=models.FloatField(default=100000),
        ),
    ]
