# Generated by Django 2.1.2 on 2018-11-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cource', '0002_auto_20181116_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='contest_mark_formula',
            field=models.CharField(default='solved * 0 + max_solved * 0 + max_possible * 0', max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='distur_mark_formula',
            field=models.CharField(default='solved * 0 + max_solved * 0 + max_possible * 0', max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='enable_disturs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='enable_marks',
            field=models.BooleanField(default=False),
        ),
    ]
