# Generated by Django 2.1.4 on 2019-01-17 23:34

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standings',
            name='enable_marks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='standings',
            name='js_for_contest_mark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='standings',
            name='js_for_total_mark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='standings',
            name='olymp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mainlink',
            name='file',
            field=models.FileField(blank=True, upload_to=courses.models.get_main_file_path),
        ),
    ]
