# Generated by Django 2.1.5 on 2019-01-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_inital'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='has_pass',
            field=models.BooleanField(default=False),
        ),
    ]
