# Generated by Django 2.0.4 on 2019-01-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_participant_has_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standings',
            name='contests',
            field=models.ManyToManyField(blank=True, related_name='standings', to='courses.Contest'),
        ),
        migrations.AlterField(
            model_name='standings',
            name='js_for_contest_mark',
            field=models.TextField(blank=True, default='var calculateContestMark = function(\n\ttotal_score,        // суммарный балл за контест\n\tproblem_score,      // массив баллов за задачи\n\tproblem_max_score,  // массив максимальных набранных баллов за задачи\n\ttotal_users,        // общее количество участников\n\tproblem_accepted   // массив количества ОК по задаче\n) {\n\treturn defaultContestMark(total_score, problem_score);\n};'),
        ),
        migrations.AlterField(
            model_name='standings',
            name='js_for_total_mark',
            field=models.TextField(blank=True, default='var calculateTotalMark = function(\n\tmarks,              // массив оценок за контесты\n\tcoefficients,        //  массив коэффициентов контесто\n\ttotal_score,        // суммарный балл за все контесты\n\tcontest_score,      // массив баллов за контесты\n\tcontest_max_score,  // массив максимальных набранных баллов за контесты\n\tproblem_score,      // двумерный массив набранных баллов за задачи\n\tproblem_max_score,  // двумерный массив максимальных набранных баллов за задач\n\ttotal_users,        // общее количество участников\n\tproblem_accepted    // двумерный массив количества ОК по задаче\n){\n\treturn defaultTotalMark(marks, coefficients);\n};'),
        ),
    ]
