# Generated by Django 2.1.5 on 2019-02-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_standings defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_raw',
            field=models.BooleanField(default=False),
        ),
    ]
