# Generated by Django 2.0.4 on 2019-02-05 16:39

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_page_is_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='photo',
            field=models.FileField(blank=True, upload_to=courses.models.get_photo_path),
        ),
        migrations.AddField(
            model_name='participant',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='courses.Person'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='courses.Person'),
        ),
    ]
