# Generated by Django 2.2 on 2019-07-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_informatics_token_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='standings',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='standings', to='courses.ParticipantsGroup'),
        ),
    ]
