# Generated by Django 2.2 on 2020-08-03 11:26

from django.db import migrations, models


def add_standings_label(apps, schema_editor):
    Standings = apps.get_model('courses', 'Standings')
    for standings in Standings.objects.all():
        standings.label = str(standings.id)
        standings.save()


def revert_standings_label(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20191122_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InformaticsToken',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='person',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='person',
        ),
        migrations.AddField(
            model_name='standings',
            name='label',
            field=models.TextField(null=True),
        ),
        migrations.RunPython(add_standings_label, revert_standings_label),
        migrations.AlterField(
            model_name='standings',
            name='label',
            field=models.TextField(unique=True),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
