# Generated by Django 2.2 on 2020-08-03 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200803_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='courses.Course'),
        ),
    ]
