# Generated by Django 3.1.1 on 2020-09-06 16:54

from django.db import migrations, models
import django.db.models.deletion


def add_main_couses(apps, schema_editor):
    MainCourse = apps.get_model('courses', 'MainCourse')
    Main = apps.get_model('courses', 'Main')
    for main in Main.objects.all():
        for course in main.courses.all():
            MainCourse.objects.create(main=main, course=course, text=course.name_in_main, url=course.url, priority=course.id)


def revert_main_couses(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200810_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='courses.course'),
        ),
        migrations.CreateModel(
            name='MainCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('url', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mains', to='courses.course')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_links', to='courses.main')),
            ],
        ),
        migrations.RunPython(add_main_couses, revert_main_couses)
    ]
