# Generated by Django 3.1.1 on 2020-09-19 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20200919_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherincourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='teacherincourse',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.teacher'),
        ),
    ]
