# Generated by Django 3.1.1 on 2020-09-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20200919_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejudgeregisterapi',
            name='use_surname',
            field=models.BooleanField(default=False),
        ),
    ]
