# Generated by Django 3.1.1 on 2020-11-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_ejudgeregisterapi_use_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_info',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_id',
            field=models.IntegerField(blank=True),
        ),
    ]
