# Generated by Django 3.1.1 on 2020-11-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20201105_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contest_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
