# Generated by Django 3.1.1 on 2021-03-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20201105_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='courses_text',
            field=models.TextField(default='Курсы'),
        ),
    ]
