# Generated by Django 3.1.1 on 2021-07-29 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20210728_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battleshipteam',
            name='course',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='battleship_teams',
        ),
        migrations.AddField(
            model_name='battleshipteam',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='battleship_teams', to='courses.ParticipantsGroup'),
        ),
        migrations.CreateModel(
            name='BattleshipParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('battleship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='courses.battleship')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battleships', to='courses.participant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='courses.battleshipteam')),
            ],
        ),
    ]
