# Generated by Django 3.1.1 on 2021-07-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20210729_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleship',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
