# Generated by Django 3.1.1 on 2021-08-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_formbuilder_formentry_formfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='formbuilder',
            name='butto_text',
            field=models.TextField(default='Отправить'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='type',
            field=models.CharField(choices=[('ST', 'Small text field'), ('IN', 'Number'), ('ML', 'Mail address'), ('PH', 'Phone number'), ('LO', 'Large textarea'), ('CB', 'Check box'), ('TX', 'Text without field')], default='ST', max_length=2),
        ),
    ]
