# Generated by Django 3.1.1 on 2021-08-09 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_auto_20210810_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formbuilder',
            old_name='butto_text',
            new_name='button_text',
        ),
    ]
