# Generated by Django 3.1.1 on 2021-08-09 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_auto_20210810_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 3, 22, 17)),
        ),
    ]
