# Generated by Django 3.1.1 on 2021-08-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_formentry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formentry',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
