# Generated by Django 3.1.1 on 2021-08-09 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_auto_20210810_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formbuilder',
            old_name='registerApi',
            new_name='register_api',
        ),
        migrations.RenameField(
            model_name='formbuilder',
            old_name='registerNameTemplate',
            new_name='register_name_template',
        ),
    ]
