# Generated by Django 3.1.1 on 2021-08-10 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_auto_20210810_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('mail_host', models.TextField()),
                ('mail_port', models.TextField()),
                ('mail_username', models.TextField()),
                ('mail_password', models.TextField()),
                ('mail_use_tls', models.BooleanField()),
                ('mail_use_ssl', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='formbuilder',
            name='mail_host',
        ),
        migrations.RemoveField(
            model_name='formbuilder',
            name='mail_password',
        ),
        migrations.RemoveField(
            model_name='formbuilder',
            name='mail_port',
        ),
        migrations.RemoveField(
            model_name='formbuilder',
            name='mail_username',
        ),
        migrations.AddField(
            model_name='formbuilder',
            name='mail_auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='courses.mailauth'),
        ),
    ]
