# Generated by Django 3.2.6 on 2021-08-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_auto_20210810_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='formbuilder',
            name='mail_topic',
            field=models.TextField(blank=True),
        ),
    ]
