# Generated by Django 3.2.6 on 2021-08-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_formbuilder_mail_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='formbuilder',
            name='ip_whitelist',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='formbuilder',
            name='requests_per_day_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
