# Generated by Django 3.2.6 on 2022-06-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_polechudesgame_polechudesguess_polechudesletter_polechudesparticipant_polechudesteam_polechudesword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polechudesgame',
            name='guess_cost',
        ),
        migrations.AddField(
            model_name='polechudesgame',
            name='accept_bonus',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polechudesgame',
            name='guess_bonus',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='polechudesletter',
            name='letter',
            field=models.CharField(max_length=1),
        ),
    ]
