# Generated by Django 3.2.6 on 2022-06-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_auto_20220621_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polechudesguess',
            old_name='wordId',
            new_name='word_id',
        ),
        migrations.AddField(
            model_name='polechudesguess',
            name='guess',
            field=models.TextField(default=''),
        ),
    ]
