# Generated by Django 3.2.6 on 2022-06-21 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0039_auto_20220621_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='polechudesteam',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pole_chudes_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
