# Generated by Django 3.2.6 on 2022-06-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_polechudesteam_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='polechudesgame',
            name='alphabet',
            field=models.TextField(blank=True, default=''),
        ),
    ]
