# Generated by Django 3.2.6 on 2022-06-21 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_polechudesgame_alphabet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polechudesteam',
            old_name='wordId',
            new_name='word_id',
        ),
        migrations.AlterField(
            model_name='polechudesgame',
            name='alphabet',
            field=models.TextField(blank=True, default='АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ'),
        ),
        migrations.AlterField(
            model_name='polechudesguess',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='courses.polechudesteam'),
        ),
        migrations.AlterField(
            model_name='polechudesletter',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='courses.polechudesteam'),
        ),
    ]
