# Generated by Django 3.2.6 on 2022-06-21 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_auto_20220622_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polechudesletter',
            old_name='wordId',
            new_name='word_id',
        ),
    ]
