# Generated by Django 3.2.6 on 2022-06-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_rename_wordid_polechudesletter_word_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='polechudesteam',
            name='players',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='polechudesteam',
            name='problems',
            field=models.IntegerField(default=0),
        ),
    ]
