# Generated by Django 3.2.6 on 2022-06-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_auto_20220622_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='polechudesteam',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
