# Generated by Django 3.2.6 on 2022-12-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_polechudesgame_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='codeforces_url',
            field=models.TextField(default='https://codeforces.com'),
        ),
    ]
