# Generated by Django 3.2.6 on 2022-12-15 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_course_codeforces_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandingsSheetExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('sheet_id', models.TextField()),
                ('tab', models.TextField()),
                ('include_penalty', models.BooleanField(default=False)),
                ('include_verdict', models.BooleanField(default=False)),
                ('include_time', models.BooleanField(default=False)),
                ('empty_columns_for_contest', models.IntegerField(default=0)),
                ('empty_beginning_columns', models.IntegerField(default=0)),
                ('standings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='courses.standings')),
            ],
        ),
    ]
