# Generated by Django 3.2.6 on 2022-12-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_standingssheetexport'),
    ]

    operations = [
        migrations.AddField(
            model_name='standingssheetexport',
            name='hide_zero_score',
            field=models.BooleanField(default=True),
        ),
    ]
