# Generated by Django 3.2.6 on 2022-12-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_standingssheetexport_hide_zero_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='standingssheetexport',
            name='calculate_mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='standingssheetexport',
            name='mark_func',
            field=models.TextField(default='\ndef calc_marks_v1(\n    user_scores, # 2d array containing all scores for users\n    contest_info, # contest info from algocode admin\n):\n    return [0] * len(user_scores)\n    \nmarks = calc_marks_v1(user_scores, contest_info)\n'),
        ),
    ]
