# Generated by Django 3.2.6 on 2022-12-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_auto_20221216_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='score_latest',
            field=models.TextField(default=False),
        ),
    ]
