# Generated by Django 3.2.6 on 2022-12-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0052_contest_score_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='score_latest',
            field=models.BooleanField(default=False),
        ),
    ]
