# Generated by Django 3.2.6 on 2022-12-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_alter_contest_score_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='score_only_finished',
            field=models.BooleanField(default=False),
        ),
    ]
