# Generated by Django 3.2.6 on 2023-05-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0054_contest_score_only_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='has_pass',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='informatics_id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='vk_id',
        ),
    ]
