# Generated by Django 3.2.6 on 2023-05-12 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0055_auto_20230512_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestUsersLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_load', to='courses.contest')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_load', to='courses.participantsgroup')),
            ],
        ),
    ]
