# Generated by Django 3.2.6 on 2023-06-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0056_contestusersload'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestusersload',
            name='use_name',
            field=models.BooleanField(default=False),
        ),
    ]
