# Generated by Django 3.2.6 on 2023-06-27 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0057_contestusersload_use_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSheetsExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('sheet_id', models.TextField()),
                ('tab', models.TextField()),
                ('latest_id', models.IntegerField(default=-1)),
                ('latest_row', models.IntegerField(default=1)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='courses.formbuilder')),
            ],
        ),
    ]
