# Generated by Django 3.2.6 on 2023-06-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0059_course_contests_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsheetsexport',
            name='do_update',
            field=models.BooleanField(default=True),
        ),
    ]
