# Generated by Django 3.2.6 on 2023-08-19 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0060_formsheetsexport_do_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='latest_reload_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 3, 0)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='judge',
            field=models.CharField(choices=[('EJ', 'Ejudge'), ('CF', 'Codeforces'), ('IN', 'Informatics'), ('EC', 'Ejudge cache')], default='EJ', max_length=2),
        ),
    ]
