# Generated by Django 3.2.6 on 2023-08-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0061_auto_20230819_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleship',
            name='problems',
            field=models.IntegerField(default=0),
        ),
    ]
