# Generated by Django 3.2.6 on 2023-09-08 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0062_battleship_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='type',
            field=models.CharField(choices=[('ST', 'Small text field'), ('IN', 'Number'), ('ML', 'Mail address'), ('PH', 'Phone number'), ('DT', 'Date'), ('LO', 'Large textarea'), ('CB', 'Check box'), ('TX', 'Text without field'), ('SL', 'Select')], default='ST', max_length=2),
        ),
        migrations.CreateModel(
            name='FormFieldSelectOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_options', to='courses.formfield')),
            ],
        ),
    ]
