# Generated by Django 3.2.6 on 2023-10-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0063_auto_20230908_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pcms_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='pcms_login',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='judge',
            field=models.CharField(choices=[('EJ', 'Ejudge'), ('CF', 'Codeforces'), ('IN', 'Informatics'), ('EC', 'Ejudge cache'), ('PC', 'PCMS')], default='EJ', max_length=2),
        ),
    ]
