# Generated by Django 4.2.10 on 2024-02-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0064_auto_20231008_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='enable_start_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
